# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7k325tffg900-2L
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/imports/XC7KSiTCPlib32k_8V/TIMER.v
  C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/imports/XC7KSiTCPlib32k_8V/SiTCP_XC7K_32K_BBT_V80.V
  C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/imports/XC7KSiTCPlib32k_8V/WRAP_SiTCP_GMII_XC7K_32K.V
}
read_vhdl -library xil_defaultlib {
  C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/new/rhea_pkg.vhd
  C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/new/sitcp.vhd
  C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/new/rbcp.vhd
  C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/new/spi_ctrl.vhd
}
read_edif C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/sources_1/imports/XC7KSiTCPlib32k_8V/SiTCP_XC7K_32K_BBT_V80.ngc
read_xdc C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/constrs_1/new/kc705.xdc
set_property used_in_implementation false [get_files C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/constrs_1/new/kc705.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.cache/wt [current_project]
set_property parent.project_dir C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl [current_project]
catch { write_hwdef -file spi_ctrl.hwdef }
synth_design -top spi_ctrl -part xc7k325tffg900-2L
write_checkpoint spi_ctrl.dcp
report_utilization -file spi_ctrl_utilization_synth.rpt -pb spi_ctrl_utilization_synth.pb
