set_property PACKAGE_PIN F16 [get_ports {gpio_led[7]}]
set_property PACKAGE_PIN E18 [get_ports {gpio_led[6]}]
set_property PACKAGE_PIN G19 [get_ports {gpio_led[5]}]
set_property PACKAGE_PIN AE26 [get_ports {gpio_led[4]}]
set_property PACKAGE_PIN AB9 [get_ports {gpio_led[3]}]
set_property PACKAGE_PIN AC9 [get_ports {gpio_led[2]}]
set_property PACKAGE_PIN AA8 [get_ports {gpio_led[1]}]
set_property PACKAGE_PIN AB8 [get_ports {gpio_led[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_led[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {gpio_led[0]}]
set_property PACKAGE_PIN T26 [get_ports {phy_rxd[6]}]
set_property PACKAGE_PIN T28 [get_ports {phy_rxd[7]}]
set_property PACKAGE_PIN T27 [get_ports {phy_rxd[5]}]
set_property PACKAGE_PIN R19 [get_ports {phy_rxd[4]}]
set_property PACKAGE_PIN U28 [get_ports {phy_rxd[3]}]
set_property PACKAGE_PIN T25 [get_ports {phy_rxd[2]}]
set_property PACKAGE_PIN U25 [get_ports {phy_rxd[1]}]
set_property PACKAGE_PIN U30 [get_ports {phy_rxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_rxd[0]}]
set_property PACKAGE_PIN J28 [get_ports {phy_txd[7]}]
set_property PACKAGE_PIN L30 [get_ports {phy_txd[6]}]
set_property PACKAGE_PIN K26 [get_ports {phy_txd[5]}]
set_property PACKAGE_PIN J26 [get_ports {phy_txd[4]}]
set_property PACKAGE_PIN L28 [get_ports {phy_txd[3]}]
set_property PACKAGE_PIN M29 [get_ports {phy_txd[2]}]
set_property PACKAGE_PIN N25 [get_ports {phy_txd[1]}]
set_property PACKAGE_PIN N27 [get_ports {phy_txd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {phy_txd[0]}]
set_property PACKAGE_PIN W19 [get_ports phy_col]
set_property PACKAGE_PIN R30 [get_ports phy_crs]
set_property PACKAGE_PIN R23 [get_ports phy_mdc]
set_property PACKAGE_PIN J21 [get_ports phy_mdio]
set_property PACKAGE_PIN L20 [get_ports phy_rstn]
set_property PACKAGE_PIN U27 [get_ports phy_rxclk]
set_property PACKAGE_PIN R28 [get_ports phy_rxctl_rxdv]
set_property PACKAGE_PIN V26 [get_ports phy_rxer]
set_property PACKAGE_PIN K30 [get_ports phy_txc_gtxclk]
set_property PACKAGE_PIN M28 [get_ports phy_txclk]
set_property PACKAGE_PIN M27 [get_ports phy_txctl_txen]
set_property PACKAGE_PIN N29 [get_ports phy_txer]
set_property IOSTANDARD LVCMOS18 [get_ports cpu_rst]
set_property PACKAGE_PIN AB7 [get_ports cpu_rst]
set_property PACKAGE_PIN Y28 [get_ports {gpio_dip_sw[3]}]
set_property PACKAGE_PIN AA28 [get_ports {gpio_dip_sw[2]}]
set_property PACKAGE_PIN W29 [get_ports {gpio_dip_sw[1]}]
set_property PACKAGE_PIN Y29 [get_ports {gpio_dip_sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_dip_sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports phy_col]
set_property IOSTANDARD LVCMOS25 [get_ports phy_crs]
set_property IOSTANDARD LVCMOS25 [get_ports phy_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports phy_mdio]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rstn]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rxclk]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rxctl_rxdv]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rxer]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txc_gtxclk]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txclk]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txctl_txen]

set_property PACKAGE_PIN AD12 [get_ports sysclk_p]
set_property IOSTANDARD LVCMOS25 [get_ports phy_txer]
set_property IOSTANDARD LVDS [get_ports sysclk_p]
set_property IOSTANDARD LVDS [get_ports sysclk_n]

# SiTCP timing constrainsts
# ref., http://openit.kek.jp/tips/member/fpga-pcb/fpga/741101568
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX10Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX11Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX12Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX13Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX14Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX15Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX16Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX17Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/BBT_SiTCP_RST/resetReq*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/memRdReq*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/orRdAct*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr*]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/muxEndTgl]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_RXBUF/cmpWrAddr*]
