set_property SRC_FILE_INFO {cfile:C:/Users/hikaru/readout/pcb_gb/fpga/rhea/spi_ctrl/spi_ctrl.srcs/constrs_1/new/kc705.xdc rfile:../../../spi_ctrl.srcs/constrs_1/new/kc705.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX10Data*]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX11Data*]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX12Data*]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX13Data*]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX14Data*]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX15Data*]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX16Data*]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX17Data*]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data*]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data*]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData*]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData*]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/BBT_SiTCP_RST/resetReq*]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/memRdReq*]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/orRdAct*]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr*]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr*]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_TXBUF/muxEndTgl]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets SiTCP_inst/Wrapper_SiTCP/SiTCP/GMII/GMII_RXBUF/cmpWrAddr*]
